### PR TITLE
Workbench theming

### PR DESCRIPTION
**Pull request by arcticicestudio**
> **Bound to** #8 

This PR migrates the theme to the new workbench theming- and JSON theme format API introduced as experimental feature in version [1.11](https://code.visualstudio.com/updates/v1_11#_preview-workbench-theming) which will be merged as stable feature in version 1.12. All commits in this PR are based on the current state of the VS Code Insiders theming API version. All attributes have been taken from [this official team member comment in Microsoft/vscode #25327](https://github.com/Microsoft/vscode/issues/25327#issuecomment-298152798).

### References
  - Official [Theme Color](https://code.visualstudio.com/docs/getstarted/theme-color-reference) documentation

## Tasks
  - [x] Increment minimal VS Code engine version to `^1.12.0`
  - [x] Update documentations
    - [x] feature section
    - [x] VS Code version badge
  - [x] Implement JSON lint gulp tasks
  - [x] Remove XML lint gulp tasks
  - [x] Update Travis CI- and Circle CI configurations

### Improvements
  - [x] [Remove transparency from all validation attributes](https://github.com/arcticicestudio/nord-visual-studio-code/pull/11#issuecomment-298765811)
    - `inputValidation.errorBackground`
    - `inputValidation.errorBorder`
    - `inputValidation.infoBackground`
    - `inputValidation.infoBorder`
    - `inputValidation.warningBackground`
    - `inputValidation.warningBorder`
    -  [x] Evaluate to change the background- or foreground color of validation *warnings* to increase the readability
  - [x] [Evaluate to change the background color of the *diff* editor to increase the readability](https://github.com/arcticicestudio/nord-visual-studio-code/pull/11#issuecomment-298765811)
  - Increase the readability and visual differentiation of `list.` attributes:
    - [x] The active- and inactive selection of unfocused- and focused list entries should differ
    - [x] The color of hovered list entries should differ from focused- and unfocused ones to provide a better visual feedback for users. This also improves navigating the list using the keyboard.
  - [x] Implement styles for *read-access* and *write-access* variable highlighting
    - `editor.wordHighlightStrongBackground`
    - `editor.wordHighlightBackground`
  - [x] Implement styles for the debug toolbar
    - `debugToolBar.background`
  - [x] Implement styles for the debug widget
    - `debugExceptionWidget.border`
    - `debugExceptionWidget.background`

### Unknown functionality
  - `editorLink.foreground`

#### Not themeable yet
  - The dimmed tab foreground color of non active editor groups](https://github.com/arcticicestudio/nord-visual-studio-code/pull/11#issuecomment-298765811)

## Unused attributes
There is no need to implement the following attributes to achieve the Nord UI style:
  - `contrastActiveBorder`
  - `contrastBorder`
  - `pickerGroup.border`

## Screenshots
<p align="center"></p>

<p align="center"><strong>Activity Bar Badges</strong><br><br><strong>Palettes</strong><br><br><strong>Tabs</strong><br><br><strong>Status Bar</strong><br><br><strong>Panel</strong><br><br><strong>Editor Widgets (Search)</strong><br><br><strong>Notifications</strong><br><br><strong>Side Bar Views (Debug)</strong><br><br><strong>Peek View</strong><br><br><strong>Diff Editor</strong><br></p>

### CODE REVIEW

**Comment by octref** [comment]
Looks so nice!

Here is a packaged VSIX if anyone also wants to help with testing: 

[nord-visual-studio-code-0.1.1.vsix.zip](https://github.com/arcticicestudio/nord-visual-studio-code/files/968074/nord-visual-studio-code-0.1.1.vsix.zip)

Will play around with it tonight and give more feedback, but for now:

- Currently selected item in Quick Launch & current file in Sidebar should be highlighted 

image

image

**Comment by octref** [comment]
Also, there is no highlight for currently selected Sidebar

image

image

**Comment by arcticicestudio** [comment]
@octref Thanks for your reports 👍 
All colors are setup correctly, but for any reason VS Code ignores them. The currently selected file in the tree-view + lists and the selected entry in a dropdown palette are styled by the attributes
  - `list.activeSelectionBackground`
  - `list.activeSelectionForeground`
  - `list.inactiveSelectionBackground`

I've even tried to overwrite them via the `workbench.colorCustomizations` setting object, but still no changes. Strangely enough the overrides work when I change the color theme 😟 
Maybe there's some kind of sequence the attributes must be ordered by in the JSON file, but this would be weird.
Either one of the other attributes overrides the ones listed above or this is a 🐞 in the theming API.

**Comment by octref** [comment]
Maybe @Tyriar would know better since he has been working with colors a lot recently.

**Comment by arcticicestudio** [comment]
@octref I've fixed it by removing the `contrastActiveBorder` and `contrastBorder` attributes which ironically also effecting the background of the styled element next to its border. I don't know if it is by design or a bug, but the names of the attributes are misleading.

**Comment by Tyriar** [comment]
@arcticicestudio Looks great! Here are some comments:

---

> I've fixed it by removing the contrastActiveBorder and contrastBorder attributes

I was under the impression `contrast*` colors only worked when you marked the theme as high contrast.

---

I actually ran into this today - don't use transparency in the validation backgrounds:

image

image

image

---

The diff background is too light imo:

image

---

If you have more than 1 editor group (a split) the non active editor group foreground is dimmed. AFAIK you can't theme this yet, it's very easy to make it unreadable:

image

---

All your list colors are very close to each other. I know you're going for a small palette and subtlety but here are some usability issues that immediately hit me:

- Active selection is the same as inactive selection - so it's easy to lose your place on what has focus
- Hover is the same as active/inactive selection - hovering the selection gives no feedback
- Navigating the list using the keyboard is a little confusing as well

**Comment by arcticicestudio** [comment]
@Tyriar Thanks for the extensive feedback 👍 
I've created some tasks from your improvement suggestions and will try to solve them today to merge this PR into the next extension release version.

> If you have more than 1 editor group (a split) the non active editor group foreground is dimmed. AFAIK **you can't theme this yet** [...]

I'll create a ticket for this as soon as it is possible to theme this elements.

**Comment by arcticicestudio** [comment]
Removed transparency from all validation attributes.
The background color of validation warnings are now using `nord12` instead of `nord13` to increase the readability.

<p align="center">
<br><br></p>

Implemented the improvement suggestions posted by @Tyriar .

Reduced the background color transparency of the *diff* editor from 75% to 30% to increase the readability.
<p align="center">

<br><p>

Increased the readability and visual differentiation of all `list.*` attributes:
  - The active- and inactive selection of unfocused- and focused list entries now differ.
  - The color of hovered list entries now differ from focused- and unfocused ones to provide a better visual feedback for users. This also improves navigating the list using the keyboard.

<p align="center"><strong>Active selection</strong><br><br><strong>Inactive selection</strong><br><br><strong>Active selection with keyboard navigation marker</strong><br><br><br><strong>Inactive selection with hover marker</strong><br><br></p>

**Comment by Tyriar** [comment]
Great job, people are going to love it ☺️👍

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension package release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.2.0).

**Comment by janpieterz** [comment]
Great stuff, been testing with the branch, loving it.

**Comment by nomenon** [comment]
Is good to use the same color for background = sideBar.background =activityBar.background ?
Much better:
  "workbench.colorCustomizations": {
    "sideBar.background": "#3B4252",
    "activityBar.background": "#485264",
    "input.background": "#485264" 
  }

**Comment by arcticicestudio** [comment]
@nomenon Nord is designed to be flat/slick and minimal. It uses the same background color to achieve a smooth transition between the components.

**Pull request merged**
