### PR TITLE
fix tab colors

### LINKED ISSUE #193: The colors of active and inactive tabs are confusing
## Description

Switch the colors of the active and inactive tabs.

### Benefits

It is more clear to the user in which tab he is currently working in. As it is now, it looks like all inactive tabs are connected to the current open document and the active one is not.

### Possible Drawbacks

None

### Alternative Solutions

Make the inactive tabs a different color than the currently open documents background color.

ui-overview-jsx

### PR DESCRIPTION
**Pull request by 1r00t**
## Description
Makes the tab bar colors less confusing

### CODE REVIEW

**Comment by 1r00t** [comment]
vscode_nord_theme_tabs
preview gif

**Review by arcticicestudio — COMMENTED** [review]
Hi @1r00t :wave:, thanks for your contribution :+1:

Nord makes use of the awesome [Refactoring UI][1] design patterns.
The principle for dark themes is that active elements should always use brighter colors to achieve the effect of making them appear “nearer“ to the user. Therefore the current style of tabs were chosen that way on purpose and this change would make it look like inactive tabs are more elevated than the active one.

> When implementing dark mode, don’t throw away the visual cues in the light version by naively inverting the color scheme.
> [][2]

Your [contribution is really appreciated][3], but I hope you can understand the decision that this change does not fully correspond to the goals of this project.

[1]: https://www.refactoringui.com
[2]: https://twitter.com/steveschoger/status/1151160261170126850?lang=en
[3]: https://opensource.guide/how-to-contribute/#communicating-effectively

**Comment by Wheels2050** [comment]
@arcticicestudio In the example you link, the active tab and the main body of the active are are all the same colour though, making them appear connected. In the VSCode theme, the tab is light while the editor background is dark which is not continuous and appears as though the tab is not connected to the editor window. I had the same issue as @1r00t in that I found it very confusing and overrode the colours to my liking.

**Comment by almenal** [comment]
What about a highlighted bounding box to the active tab, like in the ["Winter is coming" theme](https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming)?

**Pull request closed without merging**
